const { contextBridge, ipcRenderer, webUtils } = require('electron');

const call = (channel) => (...args) => ipcRenderer.invoke(channel, ...args);

contextBridge.exposeInMainWorld('hmm', {
    state: call('state'),
    toggle: call('toggle'),
    rename: call('rename'),
    remove: call('delete'),
    fixMod: call('fix-mod'),
    pickFiles: call('pick-files'),
    inspectPaths: call('inspect-paths'),
    addSources: call('add-sources'),
    saveMod: call('save-mod'),
    setOrganization: call('set-organization'),
    scanDownloads: call('scan-downloads'),
    importDownload: call('import-download'),
    openDownloads: call('open-downloads'),
    pickDownloads: call('pick-downloads'),
    launchGame: call('launch-game'),
    pickTrainer: call('pick-trainer'),
    clearTrainer: call('clear-trainer'),
    launchTrainer: call('launch-trainer'),
    setAppearance: call('set-appearance'),
    setIntroMod: call('set-intro-mod'),
    pickSplash: call('pick-splash'),
    splashFromPath: call('splash-from-path'),
    applySplash: call('apply-splash'),
    resetSplash: call('reset-splash'),
    revertSplash: call('revert-splash'),
    deleteSplashHistory: call('delete-splash-history'),
    pickGameRoot: call('pick-game-root'),
    openModsFolder: call('open-mods-folder'),
    openStorage: call('open-storage'),
    updateInfo: () => ipcRenderer.invoke('update-info'),
    checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
    downloadUpdate: () => ipcRenderer.invoke('download-update'),
    installUpdate: () => ipcRenderer.invoke('install-update'),
    onUpdateStatus: (fn) => ipcRenderer.on('update-status', (_e, data) => fn(data)),
    onDownloadsChanged: (fn) => ipcRenderer.on('downloads-changed', () => fn()),
    minimizeWindow: () => ipcRenderer.send('minimize-window'),
    maximizeWindow: () => ipcRenderer.send('maximize-window'),
    closeWindow: () => ipcRenderer.send('close-window'),
    pathForFile: (file) => webUtils.getPathForFile(file),
});
